[package]
name = "webgpu-exp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytemuck = "1.14.0"
env_logger = "0.10.0"
flume = "0.11.0"
pollster = "0.3.0"
wgpu = "0.18.0"
